### PR TITLE
change logic of create new tag type

### PR DESCRIPTION
**Pull request by wagermn**
1. Create new tag type only if it is not exists, and do nothing if it is exists.
2. Use \seq_set_from_clist:Nn instead of \xsim_set_seq_from_clist:Nn.

### CODE REVIEW

**Comment by cgnieder** [comment]
I'm tempted to reject this pull request, mainly because I don't see the reasoning behind it. Why do you want to change the logic?

**Comment by wagermn** [comment]
When many tag types are used, users may not remember what types are defined, when create an existsed tag type will issue an error. In fact, when use \DeclareExerciseTagging{TagType}, users only want to ensure the tag type TagType exists, and can use in the following text.

**Comment by cgnieder** [comment]
I'm not convinced. `\newcommand` also creates an error if the command already exists. But even if I were convinced changing the solution IMHO would be to do something like

```latex
\prg_new_conditional:Npnn \xsim_if_tag_type_exists:n #1 {T,F,TF}
  {
    \seq_if_in:NnTF \l__xsim_tag_types_seq {#1}
      { \prg_return_true: }
      { \prg_return_false: }
  }
```
and then maybe in the `interface` module

```latex
\NewDocumentCommand \ProvideExerciseTagging {m}
  {
    \xsim_if_tag_type_exists:nTF {#1}
      { \msg_warning:nnn {xsim} {tag-exists} {#1} }
      { \xsim_new_tag_type:n {#1} }
  }
```
plus defining the corresponding message rather than changing all the existing code.

**Comment by wagermn** [comment]
Maybe it is a better way.

**Comment by cgnieder** [comment]
OK. I'll add a `\ProvideExerciseTagging` to the upcoming v0.11 if that suits your needs.

**Pull request closed without merging**
